// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDspp15zNiCoMBbc4E3iGPIeuOjS8OYRuk',
    appId: '1:665143840353:web:f8285e60e8e0f461c2a420',
    messagingSenderId: '665143840353',
    projectId: 'tarot-witch-int',
    authDomain: 'tarot-witch-int.firebaseapp.com',
    storageBucket: 'tarot-witch-int.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpi1eyIg5VoOh-W2f9cLqn91BIPlxJ3SE',
    appId: '1:665143840353:android:d7a2385bf29ae29bc2a420',
    messagingSenderId: '665143840353',
    projectId: 'tarot-witch-int',
    storageBucket: 'tarot-witch-int.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhCgaThSUJ-r8F2aT2d1AqRkZvBA2dlE0',
    appId: '1:665143840353:ios:1a98cbde2b3372d4c2a420',
    messagingSenderId: '665143840353',
    projectId: 'tarot-witch-int',
    storageBucket: 'tarot-witch-int.firebasestorage.app',
    iosClientId: '665143840353-k7t0e1rlld9vq36u6t26vpt7a6m6dikc.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterTarot',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcMRSIBGQlQP8AFUH3PfeouqJY7lzQ8Ek',
    appId: '1:794860272588:ios:de6777f1e3e8fe23cabb69',
    messagingSenderId: '794860272588',
    projectId: 'tarot-a5e76',
    storageBucket: 'tarot-a5e76.firebasestorage.app',
    iosBundleId: 'com.example.flutterTarot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDspp15zNiCoMBbc4E3iGPIeuOjS8OYRuk',
    appId: '1:665143840353:web:c917544ff18e5357c2a420',
    messagingSenderId: '665143840353',
    projectId: 'tarot-witch-int',
    authDomain: 'tarot-witch-int.firebaseapp.com',
    storageBucket: 'tarot-witch-int.firebasestorage.app',
  );
}
